version: 2.1
orbs:
  cypress: cypress-io/cypress@2.1.0
workflows:
  build:
    jobs:
      - cypress/install:
          build: npm install cypress --save-dev 
      - cypress/run: 
          requires:
            - cypress/install
          wait-on: https://www.deinbett.de
          record: false # record results on Cypress Dashboard
          parallel: false # split all specs across machines
          #parallelism: 4 # use 4 CircleCI machines 
